#!/usr/bin/env bash
# This script installs Nginx and configures a 301 redirect for /redirect_me

# Update package list and install Nginx
sudo apt update -y
sudo apt install -y nginx

# Modify the default Nginx configuration file
sudo sed -i '/server_name _;/a\\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }\n' /etc/nginx/sites-available/default

# Restart Nginx using 'service' since 'systemctl' is not allowed
sudo service nginx restart
